#### Matrix 配置 - config.yml ####################################################
#
#     你好, 欢迎使用 Matrix 反作弊, 这是 config.yml, 用于定义
#  Matrix 的全局设置.
#
#  - 如果你遇到任何问题, 请加入我们的官方discord
#  群寻求帮助: https://discord.gg/pEvY55J
#
#  有用的链接:
#    官网: https://matrix.rip
#    Discord: https://discord.gg/pEvY55J
#    Wiki: https://wiki.matrix.rip
#    问题反馈: https://github.com/jiangdashao/Matrix-Issues/issues
#
#  不管怎样, 感谢使用 Matrix 反作弊!
#
#####################################################################################

# Matrix启动时应该检测更新吗？
check_update: true

# 写你的正版matrix授权密钥 https://cp.rerere.me 里面要
# 没有将是用不了matrix
access_token: 'bm7ME2zmwpUSMWTeZvaJOxw4S5FYMNpd'

# Permission Cache刷新间隔(单位:秒，默认值:15)
permission_refresh_interval: 15

#启用BungeeCord GeyserMC支持?
# Matrix支持两种运行GeyserMC的方式:
# 1。Spigot模式:在Spigot中安装GeyserMC/FloodGate，不需要修改此设置，Matrix会自动支持
# 2。Bungee Mode:在BungeeCord中安装GeyserMC时，需要启用该选项，并在BungeeCord中安装Matrix
# ! !如果您没有在BungeeCord中安装GeyserMC，请不要启用此选项
bungee_geysermc_support: false

# 如果有人使用/matrix kick，是否应该有闪电般的视觉效果
kick_strike_lightning: true

# Discord 网页注入
discord_webhook:
  # 启用 Discord 网页注入
  enable: false

  # Webhook URL
  url: ''

#服务器延迟保护
#当你的服务器滞后时自动禁用一些检查。这样可以防止
#大多数，但不是全部，误报发生。
tps_protection:
  # Enable this feature?
  enable: true

# 触发保护所需的最小TPS
  min_tps: 17.0

  # 延迟峰值
  # 如果服务器在一段时间内没有响应，则关闭检查
  lag_threshold: 1000

# 日志违规(默认为true)
# 将所有违规记录到文件中。文件可以在/plugins/Matrix/logs中找到
# 警告:如果您正在使用BungeeCord，我建议您设置
# 这将防止无用的日志文件被删除
# 正在被存储并使用宝贵的磁盘空间。
log_file: true

#删除过期的日志文件(天)
#如果日志文件的保存天数超过指定的天数，日志文件将被删除
#您可以将其设置为' -1 '来禁用此功能
delete_time: 30

# 拒绝旁路权限(默认:false)
# 通过将此选项设置为TRUE，您将强制矩阵检查每个人服务器上的，包括任何具有操作员状态的人。通过设置这个
# 选项为TRUE时，您可以运行必要的测试
disable_bypass_permission: false

## 记录时间
# 玩家被踢后多长时间可以登录(秒)
# 此外，您可以设置-1来禁用此功能
relog_time: 5

# 禁用组件
# 你可以在这里禁用一个特定的子检查，而不是禁用整个子检查
# check，您可以在详细消息的末尾找到组件名称
# 举例:如果你加上“速度”。在击网时，快速查网会
# 被禁用
disabled_components:
  - 'example entry'

#自定义VL重量(格式:component: new VL Weight)
custom_vl_weight:
  - 'example_component:5'
